### PR TITLE
r2dii.plot 0.0.1

### PR DESCRIPTION
**Pull request by maurolepore**
Relates to #313 

Following our recent conversations about implementing the Git Flow workflow, this PR proposes to merge the tag 0.0.1 into `master` (see also https://github.com/2DegreesInvesting/r2dii.plot/releases/tag/0.0.1). FYI that tag has also been submitted to CRAN.

### CODE REVIEW

**Comment by maurolepore** [comment]
This should clarify where we are at. We are now free to continue adding commits to `develop`, as the commit we submitted to CRAN is now tagged as `0.0.1` and became a [GitHub release](https://github.com/2DegreesInvesting/r2dii.plot/releases/tag/0.0.1).

```bash
* 7be1934 - (HEAD -> develop, origin/develop) Follow up initial release (#321) (33 seconds ago) <Mauro Lepore>
* eb9a879 - (tag: 0.0.1, origin/r2dii.plot-0.0.1, r2dii.plot-0.0.1) Increment version number (#318) (32 minutes ago) <Mauro Lepore>
```

**Review by AlexAxthelm — APPROVED** [review]
Exciting! 🎉

**Comment by maurolepore** [comment]
@MonikaFu, I just requested your review. It seems that @AlexAxthelm has already set up `master` to require 2 reviews.

**Review by MonikaFu — APPROVED** [review]
LGreatTM 🎉

**Pull request merged**
