### PR TITLE
Add trajectory version B 

### LINKED ISSUE #198: Add another version trajectory
Currently the user needs to specify the order of variables in specs document but it might be more convenient if they ordered the data frame itself using factors and that order would be used in the plotting function. 

Create a B-version of the function and ask users for feedback.

### PR DESCRIPTION
**Pull request by MonikaFu**
Closes #198 

In this PR I create another version of trajectory chart with simpler user interface (and requiring the user to order the data correctly before passing it to the function). See code below for use example:

``` r
library(dplyr, warn = FALSE)
devtools::load_all()
#> ℹ Loading r2dii.plot
  
data <- prep_trajectory(
  data = market_share, sector_filter = "power",
  technology_filter = "renewablescap",
  region_filter = "global", scenario_source_filter = "demo_2020",
  value_name = "production", end_year_filter = 2025,
  normalize_to_start_year = TRUE
)

# specify the order of metrics in data - first the main trajectory line, then
# the benchmarks and finally scenarios
lines_order <- c("projected", "corporate_economy", "sds", "sps", "cps")

data <- data %>%
  mutate(metric = factor(.data$metric, levels = lines_order)) %>%
  mutate(metric = dplyr::recode(
    .data$metric,
    "projected" = "Projeted",
    "corporate_economy" = "Corporate Economy",
    "sds" = "SDS",
    "sps" = "SPS",
    "cps" = "CPS")) %>%
  arrange(.data$year, .data$metric)

plot <- plot_trajectoryB(data)
plot
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

**Comment by maurolepore** [comment]
It'd be nice to see the output. Maybe use

```r
reprex::reprex(wd = ".", {
# calls to library()
devtools::load_all()
  
# code
})
```

**Comment by MonikaFu** [comment]
@maurolepore - I updated the PR description with a reprex. Is that what you meant?

**Comment by maurolepore** [comment]
@MonikaFu, as I explore I seem to find that the order does not matter -- so maybe we could not show `factor()`. Am I right or am I missing something?

This reprex messes up the order completely and yet the plot is exactly the same:

``` r
library(dplyr, warn.conflicts = FALSE)
devtools::load_all(quiet = TRUE)

data <- prep_trajectory(
  market_share,
  sector_filter = "power",
  technology_filter = "renewablescap",
  region_filter = "global",
  scenario_source_filter = "demo_2020",
  value_name = "production"
)

good_order <- c("projected", "corporate_economy", "sds", "sps", "cps")
plot_trajectoryB(mutate(data, metric = factor(.data$metric, levels = good_order))) 
```



``` r
(bad_order <- sample(good_order))
#> [1] "cps"               "sps"               "corporate_economy"
#> [4] "sds"               "projected"
# Identical
plot_trajectoryB(mutate(data, metric = factor(.data$metric, levels = bad_order)))
```



<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
@maurolepore - unfortunately I have some troubles with the reprex package now but if you arrange according to the 'bad' levels you will get a different (and undesirable) result for the trajectory lines.

`plot_trajectoryB(data %>% mutate(metric = factor(.data$metric, levels = bad_order)) %>% arrange(metric))`

**Comment by MonikaFu** [comment]
@maurolepore - see reprex with wrongly ordered data (the projected has a wrong line type). 

``` r
library(dplyr, warn.conflicts = FALSE)
devtools::load_all(quiet = TRUE)

data <- prep_trajectory(
  market_share,
  sector_filter = "power",
  technology_filter = "renewablescap",
  region_filter = "global",
  scenario_source_filter = "demo_2020",
  value_name = "production"
)

good_order <- c("projected", "corporate_economy", "sds", "sps", "cps")
plot_trajectoryB(mutate(data, metric = factor(.data$metric, levels = good_order))) 
```



``` r
(bad_order <- sample(good_order))
#> [1] "cps"               "corporate_economy" "sds"              
#> [4] "sps"               "projected"
plot_trajectoryB(data %>% mutate(metric = factor(.data$metric, levels = bad_order)) %>% arrange(metric))
```



<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maurolepore** [comment]
Thanks!
I'm tempted to add a lil helper [`order_lines()`](https://gist.github.com/maurolepore/db628daced7b5a1fb7058e78b63796d1), or to try guess the order -- can we guess based on the values we expect from the output of `r2dii.analysis::market_share()`? (i.e. `"projected", "...", "target_<scenario>"`?

**Review by maurolepore — APPROVED** [review]
LGTM. Thanks @MonikaFu!!! Even though I'm keen to follow the discussion, I think it's ready to merge.

**Comment by MonikaFu** [comment]
> Thanks!
> I'm tempted to add a lil helper [`order_lines()`](https://gist.github.com/maurolepore/db628daced7b5a1fb7058e78b63796d1), or to try guess the order -- can we guess based on the values we expect from the output of `r2dii.analysis::market_share()`? (i.e. `"projected", "...", "target_<scenario>"`?

Hmmm... Not sure here. I'm not a fan of too much guessing. To me it would obscure too much from the user. 

What we could do maybe instead of the current solution is ask the user to ass a column indicating which is the main line? And if the column is not specified we add it based on the order that is in the data?

```
data %>%
mutate(main_line = case_when(
.data$metric == "projected" ~ TRUE,
TRUE ~ FALSE))
```

**Comment by MonikaFu** [comment]
> LGTM. Thanks @MonikaFu!!! Even though I'm keen to follow the discussion, I think it's ready to merge.

@maurolepore I see that you removed the part from examples about ordering with factors but I think that it is crucial for now to stress to the users that they need to order the data correctly. Otherwise they might get lazy and not do it, still get a plot but with visual cues that are counterintuitive but not very easy to spot.. (dashed line for the most important piece of information).

**Comment by maurolepore** [comment]
Oh, sorry -- I forgot to revert once you explained the issue. I'll revert now.

**Comment by MonikaFu** [comment]
@maurolepore - alright, please revert and feel free to merge after :)

**Pull request merged**
