### PR TITLE
Add authors and roles

### PR DESCRIPTION
**Pull request by maurolepore**
We approach CRAN submission and we need to give credit to authors﻿. 

This PR:

* Adds me as an author as I wrote / reviewed a substantial amount
  of code.

* Adds Alex as an author as he oversees the development and makes
  strategic decisions.

* Adds the "contractor" role ("ctr") to everyone as I believe it
  is not us but 2DII who owns intelectual property.

Dear reviewers: 
* There may be more authors to credit. Please add them as needed. 
* Consider adding your ORCID (see the "ID" icon next to Jackson's name and mine [here](https://cran.r-project.org/web/packages/r2dii.data/index.html)).

### CODE REVIEW

**Review by MonikaFu — APPROVED** [review]
LGTM (I also added my orcid)

**Comment by maurolepore** [comment]
@AlexAxthelm as authorship is a sensitive topic I'd like a review from you too.

**Comment by AlexAxthelm** [comment]
A few thoughts on the authorship structure here:

1. I think it makes more sense for me to be listed as a Contributor (`"ctb"`), and maybe Editor (`"edt"`), or Project director (`"pdr"`). Mostly in that I don't want to diminish the authorial credit from either of you. You two did the heavy lifting in the design and implementation. If you want me listed as an author, I'm entirely okay with that, but I don't want anyone getting the impression that I did as much as you 😄 
2. @MonikaFu Do you want to be the listed maintainer (`"cre"`) (on CRAN)? If you want that, then cool, but if you'd rather that myself or Mauro take that (and the admin work that comes with it), then I'm totally okay with that.
3. I'm in the process of getting 2dii an ORCID. I won't hold up release to CRAN on that, but hopefully it comes through in the next day or two. If it does take a little while, then I'll add a new PR for the first version bump after CRANning

**Comment by AlexAxthelm** [comment]
@maurolepore, after we resolve my thoughts above, I think you might need to rebuild the `man` page

**Comment by maurolepore** [comment]
> I think it makes more sense for me to be listed as a Contributor ("ctb"), and maybe Editor ("edt"), or Project director ("pdr"). 

I think "ctb" is too light as your decisions drive the direction of the project. In `?persons` I don't see "edt" or "pdr".

> If you want me listed as an author, I'm entirely okay

I'm okay with "aut". I think your contribution is substantial -- even if not with code but ideas and decisions -- so you should appear in the package citation. `?person` reads "["aut"]: (Author) Use for full authors who have made substantial contributions to the package and should show up in the package citation.

> @MonikaFu Do you want to be the listed maintainer ("cre") (on CRAN)? 

I think you should. The skills Alex or I bring you can find on the book "R packages" or elsewhere. The skills you bring require you visualization experience. The admin work I can walk you through the first few times, then you'll be mostly fine -- just like Jackson is now.

> I'm in the process of getting 2dii an ORCID. I won't hold up release to CRAN on that

Great. I'll merge with what we have. Feel free to follow up in separate PRs if roles / ORCIDs need to be updated.

**Pull request merged**
