### PR TITLE
r2dii.plot 0.1.0 (#369)

### PR DESCRIPTION
**Pull request by maurolepore**
Relates to #369

### CODE REVIEW

**Comment by MonikaFu** [comment]
LGTM

**Review by MonikaFu — APPROVED** [review]
LGTM

**Review by MonikaFu — APPROVED** [review]
LGTM

**Comment by maurolepore** [comment]
@AlexAxthelm this PR merges the released package (now on CRAN) into `master`. We need two reviewers so please review to your earliest convenience.

**Review by AlexAxthelm — APPROVED** [review]

**Pull request merged**
