### PR TITLE
Solve merge conflicts with master

### PR DESCRIPTION
**Pull request by maurolepore**
This PR solves merge conflicts with `master` using `-Xours` to overwrite changes in `master` with changes in `develop`. 

My experiments with a toy repo indicate the merge conflicts come from my merging into `master` a squashed version of r2dii.plot-0.0.1.

    git checkout <this-branch>
    git merge -Xours origin/master

----

https://github.com/2DegreesInvesting/resources/issues/76

### CODE REVIEW

**Comment by maurolepore** [comment]
@AlexAxthelm, from our recent conversations about Git Flow I sensed I could choose to merge or squash-merge.

I chose squash-merge because it crates a clear git history, with every commit on master mapping an internal release (and maybe a CRAN release). 


```bash
# * ... next release
* 07e0025 - (origin/master, master) r2dii.plot 0.0.1 (#322) (2 hours ago) <Mauro Lepore>
* f80558b - New abort_if_multiple() hints users how to filter (#254) (10 days ago) <Mauro Lepore>
* 7d0cb96 - Redocument (#253) (11 days ago) <Mauro Lepore>
* 06dbb7c - Polish DESCRIPTION Title and Description (#252) (11 days ago) <Mauro Lepore>
* 5535d54 - Dry-run of CRAN release (#251) (11 days ago) <Mauro Lepore>
# * ... older commits
```

However at the time I did not think of merge conflicts then merging `master` back into `develop`. As I say here, the solution is simple with `-Xours` but makes feels a bit hacky so I wonder if this is part of the normal Git Flow workflow or if instead I should have merged un-squashed commits.

**Comment by maurolepore** [comment]
I'll go ahead with this solution so we keep moving `develop` forward. Yet I'm interested in following this conversation.

**Comment by AlexAxthelm** [comment]
In general, the code in `master`/`main` is what should be kept. if it has already changed in `develop`, then any of those changes can be branched and reapplied

**Comment by maurolepore** [comment]
Thanks! I think that's exactly what this branch is doing.

**Pull request merged**
