### PR TITLE
Edit articles

### PR DESCRIPTION
**Pull request by MonikaFu**
I edit the `plot_trajectoryX()` so that it uses the 'main_line' argument and Polish some of the examples in X and Y articles.

### CODE REVIEW

**Comment by MonikaFu** [comment]
@maurolepore - I'm not sure how to add links to the articles so that you can see the compiled versions from this PR.

**Review by maurolepore — APPROVED** [review]
LGTM. I'll document `main_line` in `plot_trajectoryX()` then merge.

**Comment by MonikaFu** [comment]
@maurolepore - right! Sorry for forgetting to do that!

**Comment by maurolepore** [comment]
> @maurolepore - I'm not sure how to add links to the articles so that you can see the compiled versions from this PR.
When merging into `master` the website will build automatically. Before that you may publish with  `pkgdown::deploy_to_branch()` not always a good idea but okay at this experimental stage and in this PR which does not touch production code at all -- just shows what the production code does.

**Pull request merged**
